name: Generate static site

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: '0 10 * * *'

concurrency:
  group: generate-static-site
  cancel-in-progress: true

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout main
        uses: actions/checkout@v6
        with:
          ref: main

      - name: Checkout gh-pages
        uses: actions/checkout@v6
        with:
          ref: gh-pages
          path: gh-pages

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate static site
        run: |
          python -u fetch_and_parse_ical.py ./gh-pages
        env:
          ICS_URL_OVERRIDE: ${{ secrets.ICS_URL_OVERRIDE }}

      - name: Commit changes
        run: |
          cd gh-pages
          git add .
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git diff-index --quiet HEAD || git commit -m "Update schedule data"
          git push
